// Auto-generated by deploy.yml — DO NOT EDIT manually.
// Local dev fallback. CI overwrites this with the real commit SHA before build.
export const VERSION = "dev";
export const BUILD_DATE = "local";
